[font]
size = 10 

[font.normal]
family = "RiceManFontFamily"

[colors.primary]
background = "#141720"
foreground = "#e5e5e5"

[colors.normal]
black   = "#000000"
red = "#f80101"
green   = "#00cd00"
yellow  = "#cdcd00"
blue    = "#5c5cff"
magenta = "#ff00ff"
cyan    = "#00cdcd"
white   = "#e5e5e5"

[colors.bright]
black   = "#7f7f7f"
red     = "#ff0000"
green   = "#00ff00"
yellow  = "#ffff00"
blue    = "#5c5cff"
magenta = "#ff00ff"
cyan    = "#00ffff"
white   = "#ffffff"

[colors.cursor]
cursor = "#cccccc"

[cursor.style]
shape = "Block"
blinking = "Off"

[window.padding]
x = 1
y = 1

[scrolling]
history = 10000

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
action = "ScrollPageDown"

[hints]
enabled = []
